# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
common: &common
  adapter: postgresql
  host: localhost
  timeout: 5000

development:
  <<: *common
  database: rails_gorilla_dev

test:
  <<: *common
  database: rails_gorilla_test

production:
  <<: *common
  database: rails_gorilla

